include:
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.2/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-host-qwt.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
